version: "2"
services:
  visita:
    image: visita-image
    container_name: visitaservice-container-2
    ports:
      - "8093:8093"

  pago:
    image: pago-image
    container_name: pagoservice-container-2
    ports:
      - "8092:8092"

  fatura:
    image: factura-image
    container_name: facturaservice-container-2
    ports:
      - "8091:8091"

  cliente:
    image: cliente-image
    container_name: clienteservice-container-2
    ports:
      - "8090:8090" 